feat: add (mostly complete) home page
revoltchat/frontend pull request #146
Opened 2023-02-20 08:55 UTC by Rexogamer

## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

This pull request fixes #55.

To-do:
- some styling fixes
- code cleanup
- a bit of functionality that afaict needs to be implemented elsewhere

2023-02-20 12:04 UTC, insertish requested changes

2023-02-20 12:04 UTC, insertish commented on components/client/index.tsx
> +// TODO: should this use an env variable?
Use `import.meta.env.DEV`

2023-02-20 12:04 UTC, insertish commented on packages/client/src/interface/Home.tsx
> +                            onClick={() => window.location.href = "https://insrt.uk/donate?utm_source=revolt_client_v2"} // TODO: probably want to use a different functions for this
Should open in new tab / window, also `utm_source=revoltapp` is sufficient.

2023-02-20 12:04 UTC, insertish commented on packages/client/src/interface/Home.tsx
> +                    <Column style={"margin-right: 0.25em;"}>
Hard-coded styles throughout code, if really necessary, just wrap the component:
```
const Abc = styled(Column)` margin-right: 0.25em; `;
```
Also, use margin-inline-end or whatever the equivalent is.

2023-02-20 12:04 UTC, insertish commented on packages/client/src/interface/Home.tsx
> +                    <img style="margin-top: 0.5em;" height={80} src="/assets/wide.svg" />
Also hard-coded styles, just pull them out like:
```
const Image = styled.img` margin-block-start: 0.5em; height: 80px; `;
```

2023-02-22 00:00 UTC, Rexogamer commented
Marking as ready for review - see the PR description

2023-02-22 09:54 UTC, insertish approved these changes

2023-02-22 09:55 UTC, merged