chore(deps): Update dependencies
revoltchat/frontend pull request #316
Opened 2024-10-09 17:10 UTC by Drevoed

The lockfile and the package json have become pretty dated, I have updated the versions to the latest.

Seems to be working fine except the fact that @solid-primitives/i18n got a major breaking change. But a good one, though. Needs testing.

Tauri v2 also seems to work.

Also because the repository is missing some assets I have snatched them from revite. I hope you pardon me :).

## Please make sure to check the following tasks before opening and submitting a PR

- [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/.github/blob/master/.github/CONTRIBUTING.md)
- [x] I have tested my changes locally and they are working as intended

2024-10-16 12:04 UTC, insertish requested changes
Looks good, just wondering what is going on with the logos, is this unfinished?

2024-10-16 12:04 UTC, insertish commented on packages/client/src/interface/Home.tsx
> -const Logo = styled(RevoltSvg)`
Logo is stripped out

2024-10-16 12:04 UTC, insertish commented on packages/client/components/auth/src/flows/FlowLogin.tsx
> -const Logo = styled(RevoltSvg, {
also strips logo

2024-10-16 12:04 UTC, insertish commented on packages/client/components/auth/src/flows/FlowHome.tsx
> -const Logo = styled(RevoltSvg)`
'' logo

2024-10-16 18:33 UTC, Drevoed commented
> Looks good, just wondering what is going on with the logos, is this unfinished?

It's a rudiment from trying to complete the build step locally. Seeing as the assets repo is out of bounds for me.

Will return now

2024-10-28 17:23 UTC, insertish commented
Merging locally due to lock conflict.

2024-10-28 18:29 UTC, insertish commented
Merged in 75d6c378f8add25bcfb620857699c35cfa442d54

2024-10-28 18:29 UTC, closed without merging